[build]
  command = "npm install vite && npm run build"
  publish = "dist"

[[redirects]]
  from = "/share-proxy/*"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/share"
  to = "/.netlify/functions/share"
  status = 200
  query = {id = ":id"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/manifest.json"
  to = "/assets/manifest.json"
  status = 200
